import Image from 'next/image'
import { Inter } from 'next/font/google'
import Hero from './components/Hero'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
  <div className=''>
    <Head>
      <title>Photograph Next App</title>
      <meta name='description' content='Generated by Juan A Next App' />
      <link rel='icon' href='/camera.svg' />
    </Head>
  <Hero />
  </div>
  )
}
