import Hero from './components/Hero';
import Head from 'next/head';
import Slider from './components/Slider';
import { SliderData } from './components/SliderData';
import Instagram from './components/Instagram';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photograph Next App</title>
        <meta name='description' content='Generated by Juan A Next App' />
        <link rel='icon' href='/camera.svg' />
      </Head>
      <Hero heading='Moment Photograph' message='Capturing life in a beautiful way' />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  );
}
